language: csharp
mono: 
 - latest
 - 3.12.0
 - 3.10.0
dotnet: 3.1.200
before_install:
 - cd Testing Travis CI
script:
 - dotnet restore
 - msbuild
 - dotnet test ../UnitTestProject1/bin/debug/netcoreapp3.1/UnitTestProject1.dll
